VET.Site/Models/TypeAnimals/CreateTypeAnimalsViewModel.cs
// <copyright file="CreateTypeAnimalsViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.TypeAnimals
{
    using System.ComponentModel.DataAnnotations;

    public class CreateTypeAnimalsViewModel
    {
        [Required(ErrorMessage = "El campo es obligatorio")]
        [StringLength(100, ErrorMessage = "La longitud del campo debe ser menor a 100 caracteres")]
        public string Name { get; set; }

        [StringLength(200, ErrorMessage = "La longitud del campo debe ser menor a 200 caracteres")]
        public string Description { get; set; }
    }
}

VET.Site/Models/TypeAnimals/EditTypeAnimalsViewModel.cs
// <copyright file="EditTypeAnimalsViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.TypeAnimals
{
    using System.ComponentModel.DataAnnotations;

    public class EditTypeAnimalsViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio")]
        [StringLength(100, ErrorMessage = "La longitud del campo debe ser menor a 100 caracteres")]
        public string Name { get; set; }

        [StringLength(200, ErrorMessage = "La longitud del campo debe ser menor a 200 caracteres")]
        public string Description { get; set; }
    }
}

VET.Site/Models/TypeAnimals/IndexTypeAnimalsViewModel.cs
// <copyright file="IndexTypeAnimalsViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.TypeAnimals
{
    public class IndexTypeAnimalsViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
}

VET.Site/Controllers/TypeAnimalController.cs
// <copyright file="TypeAnimalController.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.WebSite.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using VET.Core.TypeAnimals;
    using VET.DataBase.Models;
    using VET.Site.Models.TypeAnimals;

    public class TypeAnimalController : Controller
    {
        private readonly ITypeAnimalsManager typeAnimalsManager;

        public TypeAnimalController(ITypeAnimalsManager typeAnimalsManager)
        {
            this.typeAnimalsManager = typeAnimalsManager;
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Index()
        {
            var alltypeanimal = await this.typeAnimalsManager.GetAllAsync();
            var typeanimalList = alltypeanimal.Select(l => new IndexTypeAnimalsViewModel
            {
                Id = l.Id,
                Name = l.Name,
                Description = l.Description,
            });

            return this.View(typeanimalList);
        }

        [Authorize(Policy = "RequireAdminRole")]
        public IActionResult Create()
        {
            return this.View("Create");
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create(CreateTypeAnimalsViewModel createModel)
        {
            if (createModel == null)
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(createModel);
            }

            var newtypeanimal = new TypeAnimal
            {
                Name = createModel.Name,
                Description = createModel.Description,
            };

            var result = await this.typeAnimalsManager.CreateAsync(newtypeanimal);
            if (!result.Succeeded)
            {
                foreach (var kvp in result.ValidationMessages)
                {
                    foreach (var message in kvp.Value)
                    {
                        this.ModelState.AddModelError(kvp.Key, message);
                    }
                }

                return this.View(createModel);
            }

            return this.RedirectToAction("Index");
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.BadRequest();
            }

            var editList = await this.typeAnimalsManager.FindByIdAsync(id.Value);

            if (editList == null)
            {
                return this.NotFound();
            }

            var list = new EditTypeAnimalsViewModel
            {
                Id = editList.Id,
                Name = editList.Name,
                Description = editList.Description,
            };

            return this.View(list);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(EditTypeAnimalsViewModel editModel)
        {
            if (editModel == null)
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(editModel);
            }

            var typeanimalToEdit = await this.typeAnimalsManager.FindByIdAsync(editModel.Id);

            if (typeanimalToEdit == null)
            {
                return this.NotFound();
            }

            typeanimalToEdit.Description = editModel.Description;
            typeanimalToEdit.Name = editModel.Name;
            var editResult = await this.typeAnimalsManager.EditAsync(typeanimalToEdit);

            if (!editResult.Succeeded)
            {
                foreach (var kvp in editResult.ValidationMessages)
                {
                    foreach (var message in kvp.Value)
                    {
                        this.ModelState.AddModelError(kvp.Key, message);
                    }
                }

                return this.View(editModel);
            }

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.BadRequest();
            }

            var oldtypeanimal = await this.typeAnimalsManager.FindByIdAsync(id.Value);

            if (oldtypeanimal == null)
            {
                return this.NotFound();
            }

            await this.typeAnimalsManager.DeleteAsync(oldtypeanimal);

            return this.RedirectToAction("Index");
        }
    }
}

VET.Site/Views/TypeAnimal/Create.cshtml
@model VET.Site.Models.TypeAnimals.CreateTypeAnimalsViewModel
@{
    ViewData["Title"] = "Crear";
}

<div class="container-fluid">
    <!-- SELECT2 EXAMPLE -->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Crear tipo de animal.</h3>

            <div class="card-tools">
        

                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
            </div>
        </div>
        <!-- /.card-header -->
        <form method="post">
            <div class="card-body">


                @if (ViewData.ModelState[string.Empty]?.Errors?.Any() == true)
                {
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="body bg-red">
                                <div asp-validation-summary="ModelOnly"></div>
                            </div>
                        </div>
                    </div>
                }

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Nombre</label>
                            <input asp-for="Name" class="form-control" />
                            <label>
                                <span class="right badge badge-danger" asp-validation-for="Name"></span>
                            </label>

                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>Descripción</label>
                            <input asp-for="Description" class="form-control" />
                            <label >
                                <span class="right badge badge-danger " asp-validation-for="Description"></span>
                            </label>

                        </div>
                        <!-- /.form-group -->
                    </div>

                </div>
                <!-- /.row -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div align="right">
                    <a href="#confirm" class="btn btn-primary waves-effect" data-toggle="modal" data-target="#confirm">Guardar cambios</a>
                </div>
                <div class="modal fade" id="confirm" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="defaultModalLabel">Crear tipo de animal</h4>
                            </div>
                            <div class="modal-body">
                                ¿Desea crear el tipo de animal?
                            </div>
                            <div class="modal-footer">
                                <input type="submit" id="submitbutton" value="Guardar cambios" data-disableonclick="true" class="btn btn-primary waves-effect" />
                                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            </form>
    </div>
    <!-- /.card -->
</div>

VET.Site/Views/TypeAnimal/Edit.cshtml
@model VET.Site.Models.TypeAnimals.EditTypeAnimalsViewModel
@{
    ViewData["Title"] = "Editar";
}

<div class="container-fluid">
    <!-- SELECT2 EXAMPLE -->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Editar tipo de animal.</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
            </div>
        </div>
        <!-- /.card-header -->
        <form method="post">
            <div class="card-body">


                @if (ViewData.ModelState[string.Empty]?.Errors?.Any() == true)
                {
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="card">
                            <div class="body bg-red ">
                                <div asp-validation-summary="ModelOnly"></div>
                            </div>
                        </div>
                    </div>
                }

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Nombre</label>
                            <input asp-for="Name" class="form-control" />
                            <label>
                                <span class="right badge badge-danger " asp-validation-for="Name"></span>
                            </label>
                        </div>
                        <!-- /.form-group -->
                        <div class="form-group">
                            <label>Descripción</label>
                            <input asp-for="Description" class="form-control" />
                            <label>
                                <span class="right badge badge-danger" asp-validation-for="Description"></span>
                            </label>
                        </div>
                        <!-- /.form-group -->
                    </div>

                </div>
                <!-- /.row -->

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div align="right">
                    <a href="#confirm" class="btn btn-primary waves-effect" data-toggle="modal" data-target="#confirm">Guardar cambios</a>
                </div>
                <div class="modal fade" id="confirm" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="defaultModalLabel">Editar tipo de animal</h4>
                            </div>
                            <div class="modal-body">
                                ¿Desea editar el tipo de animal?
                            </div>
                            <div class="modal-footer">
                                <input type="submit" id="submitbutton" value="Guardar cambios" data-disableonclick="true" class="btn btn-primary waves-effect" />
                                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
    <!-- /.card -->
</div>

VET.Site/Views/TypeAnimal/Index.cshtml
@model IEnumerable<VET.Site.Models.TypeAnimals.IndexTypeAnimalsViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Tipos de animales</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <div class="row clearfix">
                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                        <a asp-action="Create" asp-controller="TypeAnimal" data-loader="true" class="btn btn-primary waves-effect waves-light">Crear</a>
                    </div>
                </div>
                <br />
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Opciones</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>

                                    <a asp-action="Edit" asp-route-id="@item.Id" data-loader="true" data-tooltip="tooltip" data-placement="top" title="Editar tipo de animal" class="btn btn-xs btn-table btn-circle waves-effect waves-light waves-circle">
                                        <i class="fas fa-edit"></i>
                                    </a>

                                    <a href="#confirm_@item.Id" data-tooltip="tooltip" data-placement="top" title="Eliminar tipo de animal" class="btn btn-xs btn-table btn-circle waves-effect waves-red waves-circle" data-toggle="modal" data-target="#confirm_@item.Id">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>



                                    <form asp-action="Delete" asp-route-id="@item.Id">
                                        <div class="modal fade" id="confirm_@item.Id" tabindex="-1" role="dialog">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title" id="defaultModalLabel">Eliminar tipo de animal</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        ¿Está seguro de querer eliminar el tipo de animal?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <input type="submit" value="Eliminar" data-loader="true" class="btn btn-danger waves-effect" />
                                                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        }

                    </tbody>
                    
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section scripts {
    <script>
         $(function () {
             $("#example1").DataTable({
                 "responsive": true,
                 "lengthChange": false,
                 "autoWidth": false,
                 "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                 "language": {
                     "sProcessing": "Procesando...",
                     "sLengthMenu": "Mostrar _MENU_ registros",
                     "sZeroRecords": "No se encontraron resultados",
                     "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                     "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                     "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                     "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                     "sInfoPostFix": "",
                     "sSearch": "Buscar:",
                     "sUrl": "",
                     "sInfoThousands": ",",
                     "sLoadingRecords": "Cargando...",
                     "oPaginate": {
                         "sFirst": "Primero",
                         "sLast": "Último",
                         "sNext": "Siguiente",
                         "sPrevious": "Anterior"
                     },
                     "oAria": {
                         "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                         "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                     },
                     "buttons": {
                         "copy": "Copiar",
                         "csv": "csv",
                         "excel": "excel",
                         "pdf": "pdf",
                         "print": "impresión",
                         "colvis": "Visibilidad"
                     }
                 },
                 "paging": true,
                 "searching": true,
                 "ordering": true
             }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

        });
    </script>
}