VET.Site/Models/Visits/CreateVisitsViewModel.cs
// <copyright file="CreateVisitsViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.Visits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using VET.DataBase.Models;

    public class CreateVisitsViewModel
    {
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public int AnimalId { get; set; }

        public IEnumerable<Animal> Animals { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio.")]
        public int CustomerId { get; set; }

        public IEnumerable<Customer> Customers { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public DateTime DateVisit { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio.")]
        public string VisitDetail { get; set; }

        public string NoteFirst { get; set; }

        public string NoteSeconds { get; set; }

        public string NoteThird { get; set; }
    }
}

VET.Site/Models/Visits/EditVisitsViewModel.cs
// <copyright file="EditVisitsViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.Visits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using VET.DataBase.Models;

    public class EditVisitsViewModel
    {
        public int IdModel { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio.")]
        public int AnimalId { get; set; }

        public IEnumerable<Animal> Animals { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio.")]
        public int CustomerId { get; set; }

        public IEnumerable<Customer> Customers { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public DateTime DateVisit { get; set; }

        [Required(ErrorMessage = "El campo es obligatorio.")]
        public string VisitDetail { get; set; }

        public string NoteFirst { get; set; }

        public string NoteSeconds { get; set; }

        public string NoteThird { get; set; }
    }
}

VET.Site/Models/Visits/IndexVisitViewModel.cs
// <copyright file="IndexVisitViewModel.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Models.Visits
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class IndexVisitViewModel
    {
        public int Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime DateVisit { get; set; }

        public bool IsComplet { get; set; }

        public string VisitDetail { get; set; }

        public string NoteFirst { get; set; }

        public string NoteSeconds { get; set; }

        public string NoteThird { get; set; }

        public string TypeAnimalName { get; set; }

        public string CustomerName { get; set; }
    }
}

VET.Site/Controllers/VisitsController.cs
// <copyright file="VisitsController.cs" company="SysRC">
// Copyright (c) SysRC. All rights reserved.
// </copyright>

namespace VET.Site.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using VET.Core.Animals;
    using VET.Core.Appointments;
    using VET.Core.Customers;
    using VET.DataBase.Models;
    using VET.Site.Models.Animals;
    using VET.Site.Models.Visits;

    [Route("Visits/{Action}/{Id?}")]
    public class VisitsController : Controller
    {
        private readonly IAnimalsManager animalsManager;
        private readonly IAppointmentsManager appointmentsManager;
        private readonly ICustomersManager customersManager;

        public VisitsController(
            IAnimalsManager animalsManager,
            ICustomersManager customersManager,
            IAppointmentsManager appointmentsManager)
        {
            this.animalsManager = animalsManager;
            this.appointmentsManager = appointmentsManager;
            this.customersManager = customersManager;
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Index()
        {
            var visit = await this.appointmentsManager.GetAllAsync();

            var query = visit.Select(d => new IndexVisitViewModel
            {
                Id = d.Id,
                CustomerName = d.Customers.Name,
                TypeAnimalName = d.Animals.Name,
                DateVisit = d.DateVisit,
                IsComplet = d.IsComplet,
                NoteFirst = d.NoteFirst,
                NoteSeconds = d.NoteSeconds,
                NoteThird = d.NoteThird,
                VisitDetail = d.VisitDetail,
            });

            return this.View(query);
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create()
        {
            var model = new CreateVisitsViewModel();
            model.Animals = await this.animalsManager.GetAllAsync();
            model.Customers = await this.customersManager.GetAllAsync();
            model.DateVisit = DateTime.Now;
            return this.View(model);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create(CreateVisitsViewModel createModel)
        {
            if (createModel == null)
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                createModel.Animals = await this.animalsManager.GetAllAsync();
                createModel.Customers = await this.customersManager.GetAllAsync();
                return this.View(createModel);
            }

            var customer = await this.customersManager.FindByIdAsync(createModel.CustomerId);

            if (customer == null)
            {
                return this.NotFound();
            }

            var animal = await this.animalsManager.FindByIdAsync(createModel.AnimalId);

            if (animal == null)
            {
                return this.NotFound();
            }

            animal.LastVisit = DateTime.Now;
            await this.animalsManager.EditAsync(animal);

            var newanimal = new Appointment
            {
                NoteFirst = createModel.NoteFirst,
                VisitDetail = createModel.VisitDetail,
                IsComplet = false,
                DateVisit = createModel.DateVisit,
                AnimalId = createModel.AnimalId,
                CustomerId = createModel.CustomerId,
            };

            var result = await this.appointmentsManager.CreateAsync(newanimal);
            if (!result.Succeeded)
            {
                foreach (var kvp in result.ValidationMessages)
                {
                    foreach (var message in kvp.Value)
                    {
                        this.ModelState.AddModelError(kvp.Key, message);
                    }
                }

                createModel.Animals = await this.animalsManager.GetAllAsync();
                createModel.Customers = await this.customersManager.GetAllAsync();

                return this.View(createModel);
            }

            return this.RedirectToAction("Index");
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.BadRequest();
            }

            var edit = await this.appointmentsManager.FindByIdAsync(id.Value);

            if (edit == null)
            {
                return this.NotFound();
            }

            var model = new EditVisitsViewModel
            {
                IdModel = edit.Id,
                DateVisit = edit.DateVisit,
                CustomerId = edit.CustomerId,
                NoteFirst = edit.NoteFirst,
                VisitDetail = edit.VisitDetail,
                AnimalId = edit.AnimalId,
                Animals = await this.animalsManager.GetAllAsync(),
                Customers = await this.customersManager.GetAllAsync(),
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(EditVisitsViewModel editModel)
        {
            if (editModel == null)
            {
                return this.BadRequest();
            }

            if (!this.ModelState.IsValid)
            {
                editModel.Animals = await this.animalsManager.GetAllAsync();
                editModel.Customers = await this.customersManager.GetAllAsync();
                return this.View(editModel);
            }

            var customer = await this.customersManager.FindByIdAsync(editModel.CustomerId);

            if (customer == null)
            {
                return this.NotFound();
            }

            var animal = await this.animalsManager.FindByIdAsync(editModel.AnimalId);

            if (animal == null)
            {
                return this.NotFound();
            }

            var visitToEdit = await this.appointmentsManager.FindByIdAsync(editModel.IdModel);

            if (visitToEdit == null)
            {
                return this.NotFound();
            }

            animal.LastVisit = DateTime.Now;
            await this.animalsManager.EditAsync(animal);

            visitToEdit.CustomerId = editModel.CustomerId;
            visitToEdit.AnimalId = editModel.AnimalId;
            visitToEdit.DateVisit = editModel.DateVisit;
            visitToEdit.VisitDetail = editModel.VisitDetail;
            visitToEdit.NoteFirst = editModel.NoteFirst;
            var editResult = await this.appointmentsManager.EditAsync(visitToEdit);

            if (!editResult.Succeeded)
            {
                foreach (var kvp in editResult.ValidationMessages)
                {
                    foreach (var message in kvp.Value)
                    {
                        this.ModelState.AddModelError(kvp.Key, message);
                    }
                }

                editModel.Animals = await this.animalsManager.GetAllAsync();
                editModel.Customers = await this.customersManager.GetAllAsync();
                return this.View(editModel);
            }

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.BadRequest();
            }

            var visit = await this.appointmentsManager.FindByIdAsync(id.Value);

            if (visit == null)
            {
                return this.NotFound();
            }

            await this.appointmentsManager.DeleteAsync(visit);

            return this.RedirectToAction("Index");
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Detail(int? id)
        {
            var visit = await this.appointmentsManager.FindByIdAsync(id.Value);
            if (visit == null)
            {
                return this.NotFound();
            }

            var model = new IndexVisitViewModel
            {
                Id = visit.Id,
                CustomerName = visit.Customers.Name,
                TypeAnimalName = visit.Animals.Name,
                DateVisit = visit.DateVisit,
                IsComplet = visit.IsComplet,
                NoteFirst = visit.NoteFirst,
                NoteSeconds = visit.NoteSeconds,
                NoteThird = visit.NoteThird,
                VisitDetail = visit.VisitDetail,
            };

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetAnimals(int? customerId)
        {
            var animals = await this.animalsManager.GetAllCustomerAsync(customerId.Value);

            return this.Json(animals.Select(c => new { Id = c.Id, Name = c.Name }));
        }

    }
}

VET.Site/Views/Visits/Create.cshtml
@model VET.Site.Models.Visits.CreateVisitsViewModel
@{ ViewData["Title"] = "Crear"; }

<div class="container-fluid">
    <!-- SELECT2 EXAMPLE -->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Crear Visita.</h3>

            <div class="card-tools">


                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
            </div>
        </div>
        <!-- /.card-header -->
        <form method="post">
            <div class="card-body">


                @if (ViewData.ModelState[string.Empty]?.Errors?.Any() == true)
                {
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body bg-red">
                <div asp-validation-summary="ModelOnly"></div>
            </div>
        </div>
    </div>}



                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Cliente</label>
                                <select class="form-control select2bs4 " style="width: 100%;" id="CustomerValue" asp-for="CustomerId" data-live-search="true" title="Seleccione un cliente." asp-items="@(new SelectList(Model.Customers,"Id","Name"))"></select>
                                <label>
                                    <span class="right badge badge-danger " asp-validation-for="CustomerId"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                   
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="loader animal-loader align-center" style="display:none;">
                                <div class="preloader pl-size-xs">
                                    <div class="spinner-layer pl-light-green">
                                        <div class="circle-clipper left">
                                            <div class="circle"></div>
                                        </div>
                                        <div class="circle-clipper right">
                                            <div class="circle"></div>
                                        </div>
                                    </div>
                                </div>
                                <p class="align-center">Cargando Animales...</p>
                            </div>
                            <div class="animal-select">
                                <label asp-for="AnimalId">Animal</label>
                                <div class="form-line">
                                    @if (this.Model.Animals != null)
                                    {
                        <select class="form-control select2bs4 " style="width: 100%;" id="AnimalValue" asp-for="AnimalId" data-live-search="true" data-placeholder="Seleccione un animal."  asp-items="@(new SelectList(Model.Animals,"Id","Name"))"></select> }
                    else
                    {
                        <select class="form-control select2bs4 " style="width: 100%;" id="AnimalValue" asp-for="AnimalId" data-live-search="true" data-placeholder="Seleccione un animal."></select>}
                                </div>
                            </div>
                            <label>
                                <span class="right badge badge-danger " asp-validation-for="AnimalId"></span>
                            </label>
                        </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Causa</label>
                                <input asp-for="VisitDetail" class="form-control" />
                                <label>
                                    <span class="right badge badge-danger " asp-validation-for="VisitDetail"></span>
                                </label>

                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Fecha</label>

                                <div class="input-group date" id="dateVisit" data-target-input="nearest">
                                    <input asp-for="DateVisit" type="text" data-date-format="mm/dd/yy" class="form-control datetimepicker-input" data-target="#dateVisit">
                                    <div class="input-group-append" data-target="#dateVisit" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                                <label>
                                    <span class="right badge badge-danger " asp-validation-for="DateVisit"></span>
                                </label>
                                <!-- /.input group -->
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nota</label>
                                @Html.TextAreaFor(m => m.NoteFirst, new { @class = "form-control" })
                                <label>
                                    <span class="right badge badge-danger " asp-validation-for="NoteFirst"></span>
                                </label>

                            </div>
                        </div>

                    </div>
                <!-- /.row -->

            </div>

            <div class="card-footer">
                <div align="right">
                    <a href="#confirm" class="btn btn-primary waves-effect" data-toggle="modal" data-target="#confirm">Guardar cambios</a>
                </div>
                <div class="modal fade" id="confirm" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="defaultModalLabel">Crear visita</h4>
                            </div>
                            <div class="modal-body">
                                ¿Desea crear visita?
                            </div>
                            <div class="modal-footer">
                                <input type="submit" id="submitbutton" value="Guardar cambios" data-disableonclick="true" class="btn btn-primary waves-effect" />
                                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
    <!-- /.card -->
</div>

@section scripts {
    <script>
        $(function () {
            $('.select2').select2()
            //Initialize Select2 Elements
            $(".select2bs4").prepend("<option value='' selected='selected'></option>");

            $('.select2bs4').select2({
                theme: 'bootstrap4',
                allowClear: true,
                placeholder: "Seleccione un elemento",
               
            })

            //    Date picker
            $('#dateVisit').datetimepicker({
                format: 'DD-MM-YYYY',
                todayHighlight: true,
                autoclose: true,
                language: "es"
            });

        });
        var LoaderAnimal = $('.animal-loader');
        var DivAnimal = $('.animal-select');
        var animalLoader = $('.animal-loader');
        var animalDiv = $('.animal-select');

        $('#CustomerValue').change(function () {
            LoaderAnimal.css('display', 'block');
            DivAnimal.css('display', 'none');
            var url = '@Url.Action("GetAnimals")';
            $.getJSON(url, { customerId: $('#CustomerValue').val() }, function (data) {
                $('#AnimalValue').empty();
                $.each(data, function (i, animal) {

                    $('#AnimalValue').append($('<option>', {
                        value: animal.id,
                        text: animal.name
                    }));

                });
                
                $("#AnimalValue").prepend("<option value='' selected='selected'></option>");
                $('#AnimalValue').select2({
                    theme: 'bootstrap4',
                    placeholder: "Seleccione un elemento",
                    allowClear: true
                });
                animalLoader.css('display', 'none');
                animalDiv.css('display', 'block');
            });
        });
    </script>
}

VET.Site/Views/Visits/Detail.cshtml
@model VET.Site.Models.Visits.IndexVisitViewModel
@{
    ViewData["Title"] = "Detail";
}



<div class="container-fluid">
    <!-- SELECT2 EXAMPLE -->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">Detalle visita.</h3>

            <div class="card-tools">


                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-remove"></i></button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div class="row">

                <div class="col-md-6">
                    <label>Cliente:</label>
                    @Html.DisplayFor(model => model.CustomerName)
                </div>

                <div class="col-md-6">
                    <label>Animal:</label>
                    @Html.DisplayFor(model => model.TypeAnimalName)
                </div>

                <div class="col-md-6">
                    <label>Causa:</label>
                    @Html.DisplayFor(model => model.VisitDetail)
                </div>

                <div class="col-md-6">
                    <label>Fecha:</label>
                    @Html.DisplayFor(model => model.DateVisit)
                </div>

                <div class="col-md-6">
                    <label>Nota:</label>
                    @Html.DisplayFor(model => model.NoteFirst)
                </div>
            </div>
            
            </div>
            <!-- /.row -->

        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
    </div>

VET.Site/Views/Visits/Index.cshtml
@model IEnumerable<VET.Site.Models.Visits.IndexVisitViewModel>
@{ ViewData["Title"] = "Index"; }

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Visitas</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <div class="row clearfix">
                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                        <a asp-action="Create" asp-controller="Visits" data-loader="true" class="btn btn-primary waves-effect waves-light">Crear</a>
                    </div>
                </div>
                <br />
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Cliente</th>
                            <th>Causa</th>
                            <th>Fecha</th>
                            <th>Animal</th>
                            <th>Opciones</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VisitDetail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateVisit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeAnimalName)
                </td>
             
                <td>

                    <a asp-action="Edit" asp-controller="Visits" asp-route-id="@item.Id" data-loader="true" data-tooltip="tooltip" data-placement="top" title="Editar cita" class="btn btn-xs btn-table btn-circle waves-effect waves-light waves-circle">
                        <i class="fas fa-edit"></i>
                    </a>

                    <a href="#confirm_@item.Id" data-tooltip="tooltip" data-placement="top" title="Eliminar el cita" class="btn btn-xs btn-table btn-circle waves-effect waves-red waves-circle" data-toggle="modal" data-target="#confirm_@item.Id">
                        <i class="fas fa-trash-alt"></i>
                    </a>

                    <a asp-action="Detail" asp-controller="Visits" asp-route-id="@item.Id" data-loader="true" data-tooltip="tooltip" data-placement="top" title="Detalle del cita" class="btn btn-xs btn-table btn-circle waves-effect waves-light waves-circle">
                        <i class="fas fa-arrow-right"></i>
                    </a>


                    <form asp-action="Delete" asp-route-id="@item.Id">
                        <div class="modal fade" id="confirm_@item.Id" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="defaultModalLabel">Eliminar Visita</h4>
                                    </div>
                                    <div class="modal-body">
                                        ¿Está seguro de querer eliminar visita?
                                    </div>
                                    <div class="modal-footer">
                                        <input type="submit" value="Eliminar" data-loader="true" class="btn btn-danger waves-effect" />
                                        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </td>
            </tr>
            }

                    </tbody>
                   
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section scripts {
    <script>

        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla =(",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    },
                    "buttons": {
                        "copy": "Copiar",
                        "csv": "csv",
                        "excel": "excel",
                        "pdf": "pdf",
                        "print": "impresión",
                        "colvis": "Visibilidad"
                    }
                },
                "paging": true,
                "searching": true,
                "ordering": true
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

            
           
        });
    </script>
}